# Generated by Django 3.2 on 2021-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderproduct_expecteddelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='expectedDelivery',
            field=models.DateField(blank=True, default='2099-05-31'),
        ),
    ]
